---
- hosts: lb
  become: yes
  become_user: root
  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: latest

  - name: copy conf
    template:
      src: '{{item.src}}'
      dest: '{{item.dest}}'
    loop:
    - { src: 'template/mynet-513.conf.j2', dest: '/etc/nginx/conf.d/mynet-513.conf'}
    - { src: 'template/my-site.conf.j2', dest: '/etc/nginx/conf.d/my-site.conf'}

  - name: enable nginx
    service:
      name: nginx
      enabled: yes

  - name: start nginx
    service:
      name: nginx
      state: started

  - name: install firewalld
    yum:
      name: firewalld
      state: latest
 
  - name: enable firewalld
    service:
      name: firewalld
      enabled: yes

  
  - name: start firewall
    service:
      name: firewalld
      state: started

  - name: Open firewall
    firewalld: 
      port: '{{ item }}' 
      permanent: yes 
      state: enabled 
    loop:
    - "80/tcp"
    - "443/tcp"

  - name: Restart firewalld
    service: 
      name: firewalld 
      state: restarted

  - name: restart rsyslog
    service:
      name: rsyslog
      state: restarted